stages:
    - build
    - package

build:
    image: openjdk:17
    stage: build
    script:
        - ./gradlew clean
        - ./gradlew build
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 10 min
    only:
        - dev 
    when: on_success

package:
    image: yooyoungmu/live_server_test:latest
    stage: package
    variables:
        IMAGE_NAME: yooyoungmu/live_server_test
    services:
        - docker:dind
    before_script:
        - docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
    script:
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME:latest
    after_script:
        - docker logout
    only:
        - dev
    when: on_success