spring:
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator
  server:
    port: 9090

serverName: local_server
---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 43.203.7.98
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator
  server:
    port: 9090

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 43.203.7.98
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator
  server:
    port: 9090

serverName: green_server

---