UPDATE charger
SET 
    member_price = CASE
        WHEN charging_speed = '급속' AND company_name = '환경부(협회)' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '환경부(협회)' THEN 324.4
        WHEN charging_speed = '급속' AND company_name = '차지비' THEN 335
        WHEN charging_speed = '완속' AND company_name = '차지비' THEN 269
        WHEN charging_speed = '급속' AND company_name = 'GS칼텍스' THEN 329
        WHEN charging_speed = '급속' AND company_name = 'LG유플러스' THEN 240
        WHEN charging_speed = '완속' AND company_name = 'LG유플러스' THEN 240
        WHEN charging_speed = '급속' AND company_name = 'LG유플러스(헬로비전)' THEN 240
        WHEN charging_speed = '완속' AND company_name = 'LG유플러스(헬로비전)' THEN 240
        WHEN charging_speed = '급속' AND company_name = 'SK일렉링크' THEN 385
        WHEN charging_speed = '완속' AND company_name = 'SK일렉링크' THEN 288
        WHEN charging_speed = '급속' AND company_name = '레드이엔지' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '레드이엔지' THEN 238
        WHEN charging_speed = '급속' AND company_name = '보타리에너지' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '보타리에너지' THEN 286.7
        WHEN charging_speed = '급속' AND company_name = '서울씨엔지' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '서울씨엔지' THEN 258
        WHEN charging_speed = '급속' AND company_name = '성민기업' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '성민기업' THEN 205
        WHEN charging_speed = '완속' AND company_name = '스타코프' THEN 215
        WHEN charging_speed = '급속' AND company_name = '신세계아이앤씨' THEN 324
        WHEN charging_speed = '완속' AND company_name = '신세계아이앤씨' THEN 250
        WHEN charging_speed = '급속' AND company_name = '씨어스' THEN 348
        WHEN charging_speed = '완속' AND company_name = '씨어스' THEN 324
        WHEN charging_speed = '급속' AND company_name = '아마노코리아' THEN 340
        WHEN charging_speed = '완속' AND company_name = '아마노코리아' THEN 276
        WHEN charging_speed = '급속' AND company_name = '아이마켓코리아' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '아이마켓코리아' THEN 240
        WHEN charging_speed = '급속' AND company_name = '에버온' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '에버온' THEN 229.2
        WHEN charging_speed = '완속' AND company_name = '유니이브이' THEN 234
        WHEN charging_speed = '급속' AND company_name = '이브이시스' THEN 340
        WHEN charging_speed = '완속' AND company_name = '이브이시스' THEN 250
        WHEN charging_speed = '급속' AND company_name = '이앤에이치에너지' THEN 347
        WHEN charging_speed = '완속' AND company_name = '이앤에이치에너지' THEN 196
        WHEN charging_speed = '급속' AND company_name = '이엘일렉트릭' THEN 320
        WHEN charging_speed = '완속' AND company_name = '이엘일렉트릭' THEN 260
        WHEN charging_speed = '급속' AND company_name = '이지차저' THEN 350
        WHEN charging_speed = '완속' AND company_name = '이지차저' THEN 269
        WHEN charging_speed = '급속' AND company_name = '이카플러그' THEN 340
        WHEN charging_speed = '완속' AND company_name = '이카플러그' THEN 216
        WHEN charging_speed = '급속' AND company_name = '제주전기자동차서비스' THEN 320
        WHEN charging_speed = '완속' AND company_name = '제주전기자동차서비스' THEN 280
        WHEN charging_speed = '급속' AND company_name = '지에스커넥트' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '지에스커넥트' THEN 227
        WHEN charging_speed = '급속' AND company_name = '차지인' THEN 312.5
        WHEN charging_speed = '완속' AND company_name = '차지인' THEN 292
        WHEN charging_speed = '급속' AND company_name = '대영채비' THEN 385
        WHEN charging_speed = '완속' AND company_name = '대영채비' THEN 250
        WHEN charging_speed = '급속' AND company_name = '클린일렉스' THEN 308.2
        WHEN charging_speed = '완속' AND company_name = '클린일렉스' THEN 243.2
        WHEN charging_speed = '급속' AND company_name = '타디스테크놀로지' THEN 323
        WHEN charging_speed = '완속' AND company_name = '타디스테크놀로지' THEN 242.1
        WHEN charging_speed = '급속' AND company_name = '투이스이브이씨' THEN 300
        WHEN charging_speed = '완속' AND company_name = '투이스이브이씨' THEN 280
        WHEN charging_speed = '급속' AND company_name = '파워큐브' THEN 344.4
        WHEN charging_speed = '완속' AND company_name = '파워큐브' THEN 227.8
        WHEN charging_speed = '급속' AND company_name = '파킹클라우드' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '파킹클라우드' THEN 234
        WHEN charging_speed = '완속' AND company_name = '플러그링크' THEN 220
        WHEN charging_speed = '급속' AND company_name = '한국전기차솔루션' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '한국전기차솔루션' THEN 324.4
        WHEN charging_speed = '급속' AND company_name = '한국전기차인프라기술' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '한국전기차인프라기술' THEN 255
        WHEN charging_speed = '급속' AND company_name = '한국전기차충전서비스' THEN 371
        WHEN charging_speed = '완속' AND company_name = '한국전기차충전서비스' THEN 286.7
        WHEN charging_speed = '급속' AND company_name = '한국전자금융' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '한국전자금융' THEN 266
        WHEN charging_speed = '급속' AND company_name = '한화솔루션' THEN 320
        WHEN charging_speed = '완속' AND company_name = '한화솔루션' THEN 215
        WHEN charging_speed = '급속' AND company_name = '현대엔지니어링' THEN 347
        WHEN charging_speed = '완속' AND company_name = '현대엔지니어링' THEN 260
        WHEN charging_speed = '완속' AND company_name = '홈앤서비스' THEN 227
        WHEN charging_speed = '급속' AND company_name = '휴맥스이브이' THEN 320
        WHEN charging_speed = '완속' AND company_name = '휴맥스이브이' THEN 280
        ELSE member_price
    END,
    nonmember_price = CASE
        WHEN charging_speed = '급속' AND company_name = '환경부(협회)' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '환경부(협회)' THEN 324.4
        WHEN charging_speed = '급속' AND company_name = '차지비' THEN 470
        WHEN charging_speed = '완속' AND company_name = '차지비' THEN 470
        WHEN charging_speed = '급속' AND company_name = 'GS칼텍스' THEN 430
        WHEN charging_speed = '급속' AND company_name = 'LG유플러스' THEN 350
        WHEN charging_speed = '완속' AND company_name = 'LG유플러스' THEN 350
        WHEN charging_speed = '급속' AND company_name = 'LG유플러스(헬로비전)' THEN 350
        WHEN charging_speed = '완속' AND company_name = 'LG유플러스(헬로비전)' THEN 350
        WHEN charging_speed = '급속' AND company_name = 'SK일렉링크' THEN 520
        WHEN charging_speed = '완속' AND company_name = 'SK일렉링크' THEN 520
        WHEN charging_speed = '급속' AND company_name = '레드이엔지' THEN 450
        WHEN charging_speed = '완속' AND company_name = '레드이엔지' THEN 400
        WHEN charging_speed = '급속' AND company_name = '보타리에너지' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '보타리에너지' THEN 286.7
        WHEN charging_speed = '급속' AND company_name = '서울씨엔지' THEN 400
        WHEN charging_speed = '완속' AND company_name = '서울씨엔지' THEN 400
        WHEN charging_speed = '급속' AND company_name = '성민기업' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '성민기업' THEN 292.9
        WHEN charging_speed = '완속' AND company_name = '스타코프' THEN 350
        WHEN charging_speed = '급속' AND company_name = '신세계아이앤씨' THEN 380
        WHEN charging_speed = '완속' AND company_name = '신세계아이앤씨' THEN 380
        WHEN charging_speed = '급속' AND company_name = '씨어스' THEN 348
        WHEN charging_speed = '완속' AND company_name = '씨어스' THEN 324
        WHEN charging_speed = '급속' AND company_name = '아마노코리아' THEN 440
        WHEN charging_speed = '완속' AND company_name = '아마노코리아' THEN 440
        WHEN charging_speed = '급속' AND company_name = '아이마켓코리아' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '아이마켓코리아' THEN 240
        WHEN charging_speed = '급속' AND company_name = '에버온' THEN 380
        WHEN charging_speed = '완속' AND company_name = '에버온' THEN 380
        WHEN charging_speed = '완속' AND company_name = '유니이브이' THEN 324.4
        WHEN charging_speed = '급속' AND company_name = '이브이시스' THEN 440
        WHEN charging_speed = '완속' AND company_name = '이브이시스' THEN 440
        WHEN charging_speed = '급속' AND company_name = '이앤에이치에너지' THEN 370
        WHEN charging_speed = '완속' AND company_name = '이앤에이치에너지' THEN 350
        WHEN charging_speed = '급속' AND company_name = '이엘일렉트릭' THEN 480
        WHEN charging_speed = '완속' AND company_name = '이엘일렉트릭' THEN 480
        WHEN charging_speed = '급속' AND company_name = '이지차저' THEN 450
        WHEN charging_speed = '완속' AND company_name = '이지차저' THEN 450
        WHEN charging_speed = '급속' AND company_name = '이카플러그' THEN 440
        WHEN charging_speed = '완속' AND company_name = '이카플러그' THEN 440
        WHEN charging_speed = '급속' AND company_name = '제주전기자동차서비스' THEN 480
        WHEN charging_speed = '완속' AND company_name = '제주전기자동차서비스' THEN 480
        WHEN charging_speed = '급속' AND company_name = '지에스커넥트' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '지에스커넥트' THEN 347.2
        WHEN charging_speed = '급속' AND company_name = '차지인' THEN 450
        WHEN charging_speed = '완속' AND company_name = '차지인' THEN 450
        WHEN charging_speed = '급속' AND company_name = '대영채비' THEN 500
        WHEN charging_speed = '완속' AND company_name = '대영채비' THEN 500
        WHEN charging_speed = '급속' AND company_name = '클린일렉스' THEN 403.2
        WHEN charging_speed = '완속' AND company_name = '클린일렉스' THEN 308.2
        WHEN charging_speed = '급속' AND company_name = '타디스테크놀로지' THEN 430
        WHEN charging_speed = '완속' AND company_name = '타디스테크놀로지' THEN 430
        WHEN charging_speed = '급속' AND company_name = '투이스이브이씨' THEN 400
        WHEN charging_speed = '완속' AND company_name = '투이스이브이씨' THEN 400
        WHEN charging_speed = '급속' AND company_name = '파워큐브' THEN 344.4
        WHEN charging_speed = '완속' AND company_name = '파워큐브' THEN 227.8
        WHEN charging_speed = '급속' AND company_name = '파킹클라우드' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '파킹클라우드' THEN 324.4
        WHEN charging_speed = '완속' AND company_name = '플러그링크' THEN 255.7
        WHEN charging_speed = '급속' AND company_name = '한국전기차솔루션' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '한국전기차솔루션' THEN 324.4
        WHEN charging_speed = '급속' AND company_name = '한국전기차인프라기술' THEN 380
        WHEN charging_speed = '완속' AND company_name = '한국전기차인프라기술' THEN 380
        WHEN charging_speed = '급속' AND company_name = '한국전기차충전서비스' THEN 500
        WHEN charging_speed = '완속' AND company_name = '한국전기차충전서비스' THEN 500
        WHEN charging_speed = '급속' AND company_name = '한국전자금융' THEN 347.2
        WHEN charging_speed = '완속' AND company_name = '한국전자금융' THEN 266
        WHEN charging_speed = '급속' AND company_name = '한화솔루션' THEN 480
        WHEN charging_speed = '완속' AND company_name = '한화솔루션' THEN 270
        WHEN charging_speed = '급속' AND company_name = '현대엔지니어링' THEN 500
        WHEN charging_speed = '완속' AND company_name = '현대엔지니어링' THEN 400
        WHEN charging_speed = '완속' AND company_name = '홈앤서비스' THEN 260
        WHEN charging_speed = '급속' AND company_name = '휴맥스이브이' THEN 480
        WHEN charging_speed = '완속' AND company_name = '휴맥스이브이' THEN 480
        ELSE nonmember_price
    END;